name: jenkins-agent-packer

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "TODAY=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
    - name: build :${{env.TODAY}} image
      run: |
        docker build -t ghcr.io/lazzurs/jenkins-agent-packer:${{env.TODAY}} .
    - name: publish jenkins-agent-packer:${{env.TODAY}} image
      run: |
        docker push ghcr.io/lazzurs/jenkins-agent-packer:${{env.TODAY}}
        docker tag ghcr.io/lazzurs/jenkins-agent-packer:${{env.TODAY}} ghcr.io/lazzurs/jenkins-agent-packer:latest
        docker push ghcr.io/lazzurs/jenkins-agent-packer:latest
    - name: Login to Docker Hub registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_KEY }}
    - name: publish jenkins-agent-packer:${{env.TODAY}} image to Docker Hub
      run: |
        docker tag ghcr.io/lazzurs/jenkins-agent-packer:${{env.TODAY}} lazzurs/jenkins-agent-packer:latest
        docker tag ghcr.io/lazzurs/jenkins-agent-packer:${{env.TODAY}} lazzurs/jenkins-agent-packer:${{env.TODAY}}
        docker push lazzurs/jenkins-agent-packer:${{env.TODAY}}
        docker push lazzurs/jenkins-agent-packer:latest

